const data = {
    products:[
        {
            _id: '1',
            name:'Äpple',
            category:'frukter',
            image:'/images/apple.png',
            price:60,
            countInStock:10,
            brand:'Healthy fruit',
            rating:4.5,
            numReviews:10,
            description:'Högkvalitativ färsk produkt',
        },
        {
            _id: '2',
            name:'Banan',
            category:'frukter',
            image:'/images/banana.png',
            price:40,
            countInStock:15,
            brand:'Frisk frukt',
            rating:5.5,
            numReviews:8,
            description:'Högkvalitativ färsk produkt',
        },
        {
            _id: '3',
            name:'Vindruvor',
            category:'frukter',
            image:'/images/grape.png',
            price:80,
            countInStock:20,
            brand:'Frisk frukt',
            rating: 2.5,
            numReviews:5,
            description:'Högkvalitativ färsk produkt',
        },
        {
            _id: '4',
            name:'Citron',
            category:'frukter',
            image:'/images/lemon.png',
            price:60,
            countInStock:10,
            brand:'Frisk frukt',
            rating:3.5,
            numReviews:9,
            description:'Högkvalitativ färsk produkt',
        },
        {
            _id: '5',
            name:'Mango',
            category:'frukter',
            image:'/images/mango.png',
            price:120,
            countInStock:0,
            brand:'Frisk frukt',
            rating:5.0,
            numReviews:10,
            description:'Högkvalitativ färsk produkt',
        },
        {
            _id: '6',
            name:'Apelsin',
            category:'frukter',
            image:'/images/orange.png',
            price:35,
            countInStock:40,
            brand:'Frisk frukt',
            rating:4.5,
            numReviews:8,
            description:'Högkvalitativ färsk produkt',
        },
        {
            _id: '7',
            name:'Ananas',
            category:'frukter',
            image:'/images/pineapple.png',
            price:100,
            brand:'Frisk frukt',
            rating:4.5,
            numReviews:10,
            description:'Högkvalitativ färsk produkt',
        },
        {
            _id: '8',
            name:'Jordgubber',
            category:'frukter',
            image:'/images/strawberry.png',
            price:50,
            countInStock:10,
            brand:'Frisk frukt',
            rating:4.5,
            numReviews:10,
            description:'Högkvalitativ färsk produkt',
        },
        {
            _id: '9',
            name:'Morot',
            category:'Grönsaker',
            image:'/images/carrot.png',
            price:60,
            countInStock:20,
            brand:'färsk grönsak',
            rating:4.5,
            numReviews:10,
            description:'Högkvalitativ färsk produkt',
        },
        {
            _id: '10',
            name:'Tomot',
            category:'Grönsaker',
            image:'/images/tomato.png',
            price:20,
            countInStock:30,
            brand:'färsk grönsak',
            rating:4.0,
            numReviews:6,
            description:'Högkvalitativ färsk produkt',
        },
        {
            _id: '11',
            name:'Kål',
            category:'Grönsaker',
            image:'/images/cabbage.png',
            price:30,
            countInStock:5,
            brand:'färsk grönsak',
            rating:4.5,
            numReviews:7,
            description:'Högkvalitativ färsk produkt',
        },
        {
            _id: '12',
            name:'Broccoli',
            category:'Grönsaker',
            image:'/images/broccoli.png',
            price:40,
            countInStock:10,
            brand:'färsk grönsak',
            rating:3.5,
            numReviews:5,
            description:'Högkvalitativ färsk produkt',
        },
        {
            _id: '13',
            name:'Potatis',
            category:'Grönsaker',
            image:'/images/potato.png',
            price:35,
            countInStock:40,
            brand:'färsk grönsak',
            rating:4.5,
            numReviews:10,
            description:'Högkvalitativ färsk produkt',
        },
        {
            _id: '14',
            name:'Röd-chili-pepper',
            category:'Grönsaker',
            image:'/images/red-chili-pepper.png',
            price:55,
            countInStock:15,
            brand:'färsk grönsak',
            rating:3.5,
            numReviews:6,
            description:'Högkvalitativ färsk produkt',
        },
        {
            _id: '15',
            name:'Lök',
            category:'Grönsaker',
            image:'/images/onion.png',
            price:45,
            countInStock:10,
            brand:'färsk grönsak',
            rating:4.5,
            numReviews:8,
            description:'Högkvalitativ färsk produkt',
        },
        {
            _id: '16',
            name:'Majs',
            category:'Grönsaker',
            image:'/images/corn.png',
            price:30,
            countInStock:17,
            brand:'färsk grönsak',
            rating:4.5,
            numReviews:10,
            description:'Högkvalitativ färsk produkt',
        },
        {
            _id: '17',
            name:'Gurka',
            category:'Grönsaker',
            image:'/images/cucumber.png',
            price:15,
            countInStock:25,
            brand:'färsk grönsak',
            rating:4.5,
            numReviews:5,
            description:'Högkvalitativ färsk produkt',
        },
        {
            _id: '18',
            name:'Aubergine',
            category:'Grönsaker',
            image:'/images/eggplant.png',
            price:40,
            countInStock:10,
            brand:'färsk grönsak',
            rating:4.8,
            numReviews:6,
            description:'Högkvalitativ färsk produkt',
        },
    ],
};
export default data;